name: 'Docs conversion'
author: 'Shay DeWael'
description: 'Parse and convert markdown files using YAML templates'
branding:
  icon: book-open
  color: blue
inputs:
  repo-token:
      description: 'The GITHUB_TOKEN secret'
      required: true
  schema:
    description: 'Defines schema used to parse content'
    required: true
    default: ''
  input:
    description: 'Directories contain the .md files'
    required: false
  output:
    description: 'Directory to ouput files'
    required: false
    default: 'docs/compiled'
  components:
    description: 'Array of document components'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'